### ISSUE TITLE
Adapt API to download only desired files from dataverse according to user request.

### ISSUE THREAD

**Issue by mauriciogtec** [NSAPH-Projects/space#10]

**Comment by atrisovic** [comment]
If `nn` download:

- counties.geojson
- counties.graphml
- medisynth-nn-binary.csv
- medisynth-nn-binary.json
- medisynth-nn-continuous.csv
- medisynth-nn-continuous.json

If `xgboost` download:

- counties.geojson
- counties.graphml
- medisynth-xgboost-binary.csv
- medisynth-xgboost-binary.json
- medisynth-xgboost-continuous.csv

medisynth-xgboost-continuous.json

**Comment by atrisovic** [comment]
This one could also be closed now with #36. Or we can rename it to 'add text file to document available datasets'

**Comment by mauriciogtec** [comment]
Closed by #42
