### ISSUE TITLE
Set a default path for bash API

### ISSUE THREAD

**Issue by mauriciogtec** [NSAPH-Projects/space#11]

**Comment by mauriciogtec** [comment]
@atrisovic There's no current default path for the bash API. Do we want one?

**Comment by mauriciogtec** [comment]
@atrisovic Can we close this? What is the default path in the cli? Should be where the cli is called.

**Comment by atrisovic** [comment]
It has a default when downloading, but it doesn't have a default when saving the generated file and that info will be required from the user. We can close this now or with my next PR (in making).
