### ISSUE TITLE
Change the python package name (space-bench suggested)

### ISSUE THREAD

**Issue by mauriciogtec** [NSAPH-Projects/space#28]
Since space is taken in the Python registry, a new name must be chosen. space-bench is available.

As per conversion, the code would be invoked from Python as
```python
import space_bench
```

Or
```python
import space_bench as space
```

**Comment by Naeemkh** [comment]
I like the name, although the use of underscores is discouraged ([PEP8](https://peps.python.org/pep-0008/#package-and-module-names)). How about `spacebench`?
