### ISSUE TITLE
Metadata for downloaded data

### ISSUE THREAD

**Issue by Naeemkh** [NSAPH-Projects/space#55]
Currently, we can download the data, but there is no accompanying information about how it was generated, the internal parameters used, or the meanings of the different columns. It would be helpful to have a separate file containing this metadata along with the data.

**Comment by Naeemkh** [comment]
I used the following command and only `.csv` file is downloaded. There might be a bug.

```sh
spacebench nn binary 10 --output_path $PWD

```

**Comment by mauriciogtec** [comment]
@atrisovic can you look into this? if the metada is not downloaded the whole thing will crash.

**Comment by Naeemkh** [comment]
@atrisovic, @mauriciogtec,  this issue has already been resolved. Correct?

**Comment by mauriciogtec** [comment]
Yes. Closing. :)
