### ISSUE TITLE
Improve Documentation Across All Classes and Functions

### ISSUE THREAD

**Issue by Naeemkh** [NSAPH-Projects/space#56]
There are several classes and functions in our codebase that lack sufficient documentation, particularly regarding their arguments. This issue aims to address and rectify this gap.

The goal is to ensure that all classes and modules in the project have comprehensive and clear documentation. The documentation should include, but not limited to, an overview of what each class or function does, descriptions of all arguments and their expected types, and what the function returns if applicable.

This task will be considered successful when every class and function in the project is properly documented, enhancing readability and maintainability of our codebase.

**Comment by mauriciogtec** [comment]
Closing since this issue was for release v0.0.2.
