### ISSUE TITLE
Python API for downloading data

### ISSUE THREAD

**Issue by Naeemkh** [NSAPH-Projects/space#60]
It is necessary to develop a Python API that enables data downloading and maintains a persistent connection for future data loaders. All download and processing operations should be conducted within a Python session, rather than a shell script.

**Comment by mauriciogtec** [comment]
Modify masterfile to include:

- name
- task (binary,continuous)
- spatial_smoothness
- confounding_level
- has_coordinates

**Comment by audiracmichelle** [comment]
error sampler will be moved https://github.com/NSAPH-Projects/space-data

**Comment by mauriciogtec** [comment]
Solved with refactoring in #63
