### ISSUE TITLE
Merge spatial+ algo

### ISSUE THREAD

**Issue by sophi890** [NSAPH-Projects/space#64]
This is a B-spline implementation, which allowed us to directly use python's GLMGam from statsmodels. 
If time could try to replace the B spline with TPS (TPS did not have same attributes that would allow us to plug into GLMGam).
Also need to add statsmodels to the dependencies in the requirements yaml.

Accommodates binary exposure and continuous exposure.

**Comment by mauriciogtec** [comment]
Solved in #78
